api: "1.0"
main: de.ironaxe.commandcentral.CommandCentralBukkit
author: kiwi
name: CommandCentral
description: Command suggestion firewall for Bukkit and Waterfall
version: "${project.version}"
api-version: 1.18
