main: de.ironaxe.commandcentral.CommandCentralBukkit
author: kiwi
name: CommandCentral
description: ${plugin.description}
version: "${plugin.version}"
api-version: 1.13
softdepend: [ LuckPerms ]
website: https://www.spigotmc.org/resources/commandcentral-clean-up-your-command-suggestion-list.111277/