name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          architecture: x64
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: target/CommandCentral.jar